### ISSUE TITLE
Server类中getServer()如何使用？

### ISSUE THREAD

**Issue by xkungfu** [jimmyfen/websocket-server#1]
调用$this->getServer();
报错：PHP Fatal error:  Uncaught TypeError: Return value of Websocket\process\Server::getServer() must be an instance of Websocket\process\Server

**Comment by jimmyfen** [comment]
感谢提出bug，我会尽快修复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xkungfu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 中午11:34
收件人:&nbsp;"jimmyfen/websocket-server"<websocket-server@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jimmyfen/websocket-server] Server类中getServer()如何使用？ (#1)




调用$this-&gt;getServer();
 报错：PHP Fatal error:  Uncaught TypeError: Return value of Websocket\process\Server::getServer() must be an instance of Websocket\process\Server

**Comment by xkungfu** [comment]
Return value of Websocket\process\Server::getServer() 

must be an instance of Websocket\process\Server, 

instance of Swoole\WebSocket\Server returned

**Comment by xkungfu** [comment]
看报错提示好像是说，Websocket\process\Server 和 Swoole\WebSocket\Server搞串了。不知道这个函数原本是打算返回哪个实现的server.

**Comment by jimmyfen** [comment]
原本是要返回swoole_websocket_server实例，返回类型写错了，已经去掉了

**Comment by jimmyfen** [comment]
目前可以在master分支上看到

**Comment by xkungfu** [comment]
问题解决了！谢谢！

**Comment by jimmyfen** [comment]
感谢使用支持！
